custom:
    thumbnailUrl: "C:\\Users\\Admin\\Desktop\\payday-trade\\src\\main\\resources\\thumbnail\\thumbnail"
    imagesUrl: "C:\\Users\\Admin\\Desktop\\payday-trade\\src\\main\\resources\\images\\product"

